baseurl = "https://nipo-plus-doc.sndbox.jp/"
canonifyURLs = false
disableAliases = false
disableHugoGeneratorInject = false
enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
paginate = 30
rssLimit = 10

# Multilingual
defaultContentLanguage = "ja"
disableLanguages = ["en"]
# defaultContentLanguageInSubdir = true

# add redirects/headers
[outputs]
home = ["HTML", "RSS", "Algolia"]
section = ["HTML", "RSS", "SITEMAP"]

# add output format for section sitemap.xml
[outputFormats.SITEMAP]
mediaType = "application/xml"
baseName = "sitemap"
isHTML = false
isPlainText = true
noUgly = true
rel  = "sitemap"


[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true


[caches]
  [caches.getjson]
    dir = ":cacheDir/:project"
    maxAge = "10s"

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.6

[taxonomies]
  tag = "tags"


[minify.tdewolff.html]
  keepWhitespace = false

[related]
  threshold = 80
  includeNewer = true
  toLower = false
    [[related.indices]]
    name = "tags"
    weight = 100
    [[related.indices]]
    name = "date"
    weight = 10


[frontmatter]
  date = ["date", "publishDate", "lastmod", ":default"]
  lastmod = [":git", "lastmod", "date", "publishDate"]

[build]
  writeStats = true