baseurl = "https://nipo-plus-doc.sndbox.jp/"
canonifyURLs = false
disableAliases = false
disableHugoGeneratorInject = true
enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
paginate = 30
rssLimit = 10

# Multilingual
defaultContentLanguage = "ja"
disableLanguages = ["en"]
# defaultContentLanguageInSubdir = true

# add redirects/headers
[outputs]
home = ["HTML", "RSS", "REDIRECTS", "HEADERS", "Algolia"]
section = ["HTML", "RSS", "SITEMAP"]

# remove .{ext} from text/netlify
[mediaTypes."text/netlify"]
suffixes = [""]
delimiter = ""

# add output format for netlify _redirects
[outputFormats.REDIRECTS]
mediaType = "text/netlify"
baseName = "_redirects"
isPlainText = true
notAlternative = true

# add output format for netlify _headers
[outputFormats.HEADERS]
mediaType = "text/netlify"
baseName = "_headers"
isPlainText = true
notAlternative = true

# add output format for section sitemap.xml
[outputFormats.SITEMAP]
mediaType = "application/xml"
baseName = "sitemap"
isHTML = false
isPlainText = true
noUgly = true
rel  = "sitemap"


[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true


[caches]
  [caches.getjson]
    dir = ":cacheDir/:project"
    maxAge = "10s"

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[taxonomies]
  # contributor = "contributors"
  category = "categories"
  tag = "tags"

# [permalinks]
  # blog = "/blog/:title/"
# docs = "/docs/1.0/:sections[1:]/:title/"

[minify.tdewolff.html]
  keepWhitespace = false

[related]
  threshold = 80
  includeNewer = true
  toLower = false
    [[related.indices]]
    name = "categories"
    weight = 40
    [[related.indices]]
    name = "tags"
    weight = 100
    [[related.indices]]
    name = "date"
    weight = 10


[frontmatter]
  date = ["date", "publishDate", "lastmod", ":default"]
  lastmod = ["lastmod", ":git", "date", "publishDate"]

[build]
  writeStats = true