# [en]
#   languageName = "English"
#   contentDir = "content/en"
#   weight = 20
#   [en.params]
#     languageISO = "EN"
#     languageTag = "en-US"
#     footer = 'Brought to you by <a class="text-muted" href="https://thulite.io/">Thulite</a>'
#     alertText = '<a class="alert-link stretched-link fw-normal" href="/blog/example-post/">Doks version 1.0 just shipped!</a>'

[ja]
  languageName = "日本語"
  contentDir = "content/ja"
  weight = 10
  [ja.params]
    languageISO = "JA"
    languageTag = "ja-JP"
    titleAddition = "NipoPlus Document"
    description = "クラウド日報 NipoPlus公式Webサイト。操作マニュアルやご利用料金、様々な利用方法について紹介しております。ご利用料金は1名180円の低価格。無料プランの用意もございます。"
    titleHome = "クラウド日報 NipoPlus"
    footer = '開発運営:<a href="https://sndbox.jp/">合同会社サンドボックス</a> / 協力: <a href="https://pandafirm.jp/">パンダ商会</a>'
    alertText = 'Welcome to NipoPlus'
