[hugoVersion]
  extended = true
  min = "0.80.0"
  max = ""

# [[mounts]]
#   source = "node_modules/flexsearch"
#   target = "assets/js/vendor/flexsearch"

# [[mounts]]
#   source = "node_modules/katex"
#   target = "assets/js/vendor/katex"

[[mounts]]
  source = "node_modules/mermaid"
  target = "assets/js/vendor/mermaid"

[[mounts]]
  source = "assets"
  target = "assets"
