
[[main]]
  name = "操作ガイド"
  url = "/docs/manual/quickstart/"
  weight = 10
[[main]]
  name = "ユースケース"
  url = "/tips/"
  weight = 11

[[main]]
  name = "料金"
  url = "/docs/price/_about/"
  weight = 20

[[main]]
  name = "inquery"
  url = "/others/inquery/"
  weight = 40


[[main]]
  name = "ブログ"
  weight = 50
  identifier = "blogroot"
  url = ""

[[main]]
  name = "ニュース"
  weight = 51
  identifier = "news"
  url = "/news/"
  parent = "blogroot"

[[main]]
  name = "技術系ブログ"
  weight = 52
  identifier = "tech"
  url = "/tech/"
  parent = "blogroot"
